CREATE TABLE ALBUM(
	ALBUMNAME VARCHAR(100), 
	YEAR VARCHAR(4), 
	TRACKCOUNT INT, 
	ARTISTID BIGINT NOT NULL, 
	ALBUMID BIGINT NOT NULL IDENTITY);
CREATE TABLE ARTIST(
    ARTISTNAME VARCHAR(100),
    ARTISTID BIGINT NOT NULL IDENTITY);
CREATE TABLE PLAYLIST(
	PLAYLISTNAME VARCHAR(100),
	PLAYLISTID BIGINT NOT NULL IDENTITY);
CREATE TABLE PLAYLISTENTRY(
	SONGID BIGINT NOT NULL,
	PLAYLISTID BIGINT NOT NULL, 
	PLAYLISTENTRYID BIGINT NOT NULL IDENTITY);
CREATE TABLE SONG(
	SONGNAME VARCHAR(100), 
	URL VARCHAR(255), 
	TRACKNUMBER INT, 
	LENGTH INT, 
	GENRE BIGINT, 
	FILECREATEDATE DATETIME, 
	ALBUMID BIGINT NOT NULL, 
	SONGID BIGINT NOT NULL IDENTITY);
CREATE TABLE GENRE(
	GENREID INTEGER NOT NULL IDENTITY,
	GENRENAME VARCHAR(30) NOT NULL);
CREATE TABLE TAG(
	TAGID BIGINT NOT NULL IDENTITY,
	TAGNAME VARCHAR(30),
	TAGDESCRIPTION VARCHAR(255));
CREATE TABLE USER(
	USERID BIGINT NOT NULL IDENTITY,
	USERNAME VARCHAR(15) NOT NULL,
	PASSWORD VARCHAR(36) NOT NULL);
CREATE TABLE ROLE(
	ROLEID BIGINT NOT NULL IDENTITY,
	ROLENAME VARCHAR(30) NOT NULL,
	ROLEDESCRIPTION VARCHAR(255));
CREATE TABLE USERROLE(
    USERROLEID BIGINT NOT NULL IDENTITY,
    USERID  BIGINT NOT NULL,
    ROLEID BIGINT NOT NULL);
ALTER TABLE ALBUM ADD FOREIGN KEY ( ARTISTID) REFERENCES ARTIST (ARTISTID);
ALTER TABLE SONG ADD FOREIGN KEY (ALBUMID) REFERENCES ALBUM(ALBUMID);
ALTER TABLE SONG ADD FOREIGN KEY ( GENRE ) REFERENCES GENRE(GENREID);
ALTER TABLE PLAYLISTENTRY ADD FOREIGN KEY ( PLAYLISTID ) REFERENCES PLAYLIST (PLAYLISTID);
ALTER TABLE PLAYLISTENTRY ADD FOREIGN KEY (SONGID ) REFERENCES SONG(SONGID);
ALTER TABLE USERROLE ADD FOREIGN KEY ( USERID ) REFERENCES USER (USERID);
ALTER TABLE USERROLE ADD FOREIGN KEY ( ROLEID ) REFERENCES ROLE (ROLEID);
CREATE TABLE SONGTAG ( 
   SONGTAGID BIGINT NOT NULL IDENTITY, 
   SONGID BIGINT NOT NULL,
   TAGID BIGINT NOT NULL
) ;
ALTER TABLE SONGTAG ADD FOREIGN KEY ( SONGID ) REFERENCES SONG(SONGID);
ALTER TABLE SONGTAG ADD FOREIGN KEY (TAGID) REFERENCES TAG (TAGID);
CREATE TABLE USERTAG (
	USERTAGID BIGINT NOT NULL IDENTITY,
	USERID BIGINT NOT NULL,
	TAGID BIGINT NOT NULL);
ALTER TABLE USERTAG ADD FOREIGN KEY (USERID) REFERENCES USER (USERID);
ALTER TABLE USERTAG ADD FOREIGN KEY (TAGID) REFERENCES TAG (TAGID);
